language: clojure
lein: lein2
script: lein2 test
services:
  - postgresql
before_script:
  - psql -c 'create database relational_mapper_test;' -U postgres
notifications:
  recipients:
    - krzysiek.herod@gmail.com
jdk:
  - oraclejdk8
